"""Deterministic C header generation from validated CSR IR."""

from __future__ import annotations

from pathlib import Path

from .checker import SemanticChecker
from .model import RegisterBlock


class CHeaderGenerator:
    """Generate register offsets and field mask/shift macros."""

    def __init__(self, block: RegisterBlock):
        self.block = SemanticChecker().validate(block)

    def render(self) -> str:
        guard = f"CSRFORGE_{self.block.name.upper()}_H"
        lines = [
            "/* Generated by CSRForge. Do not edit manually. */",
            f"#ifndef {guard}",
            f"#define {guard}",
            "",
        ]

        for register in self.block.registers:
            register_name = register.name.upper()
            lines.append(
                f"#define CSR_{register_name}_OFFSET "
                f"0x{register.offset:08X}u"
            )
            for field in register.fields:
                field_name = field.name.upper()
                mask = ((1 << field.width) - 1) << field.lsb
                prefix = f"CSR_{register_name}_{field_name}"
                lines.append(f"#define {prefix}_MASK 0x{mask:08X}u")
                lines.append(f"#define {prefix}_SHIFT {field.lsb}u")
            lines.append("")

        lines.extend([f"#endif /* {guard} */", ""])
        return "\n".join(lines)

    def write(self, output_path: str | Path) -> Path:
        path = Path(output_path)
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(self.render(), encoding="utf-8", newline="\n")
        return path

