"""Deterministic Markdown register-map generation."""

from __future__ import annotations

from pathlib import Path

from .checker import SemanticChecker
from .model import Field, RegisterBlock


def _bits(field: Field) -> str:
    return str(field.lsb) if field.width == 1 else f"{field.msb}:{field.lsb}"


class MarkdownGenerator:
    """Generate a concise human-readable register map."""

    def __init__(self, block: RegisterBlock):
        self.block = SemanticChecker().validate(block)

    def render(self) -> str:
        lines = [
            f"# {self.block.name} Register Map",
            "",
            "Generated by CSRForge from validated Canonical IR.",
            "",
            "- Bus: APB3",
            f"- Data width: {self.block.data_width} bit",
            "- Addressing: local byte offsets",
            "",
        ]

        for register in self.block.registers:
            lines.extend([
                f"## {register.name} — 0x{register.offset:08X}",
                "",
                "| Field | Bits | Access | Reset | Mask |",
                "| --- | ---: | --- | ---: | ---: |",
            ])
            for field in register.fields:
                mask = ((1 << field.width) - 1) << field.lsb
                lines.append(
                    f"| {field.name} | {_bits(field)} | {field.access} | "
                    f"0x{field.reset:X} | 0x{mask:08X} |"
                )
            lines.append("")

        return "\n".join(lines)

    def write(self, output_path: str | Path) -> Path:
        path = Path(output_path)
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(self.render(), encoding="utf-8", newline="\n")
        return path

