"""Deterministic SystemVerilog RTL generation from validated CSR IR."""

from __future__ import annotations

from pathlib import Path

from .checker import SemanticChecker
from .model import Field, Register, RegisterBlock


def _base_name(register: Register, field: Field) -> str:
    return f"{register.name}_{field.name}".lower()


def _port_name(register: Register, field: Field) -> str:
    base = _base_name(register, field)
    if field.access == "RW":
        return f"{base}_o"
    if field.access == "RO":
        return f"{base}_i"
    return f"{base}_set_i"


def _state_name(register: Register, field: Field) -> str:
    return f"{_base_name(register, field)}_q"


def _addr_name(register: Register) -> str:
    return f"{register.name.upper()}_ADDR"


def _compact_range(field: Field) -> str:
    return "" if field.width == 1 else f"[{field.width - 1}:0] "


def _bus_slice(field: Field) -> str:
    if field.width == 1:
        return f"[{field.lsb}]"
    return f"[{field.msb}:{field.lsb}]"


def _sv_literal(width: int, value: int) -> str:
    return f"{width}'b{value:0{width}b}"


class RtlGenerator:
    """Render an explicit APB3 CSR slave from a validated register block."""

    def __init__(self, block: RegisterBlock):
        self.block = SemanticChecker().validate(block)

    def render(self) -> str:
        lines: list[str] = [
            "// Generated by CSRForge. Do not edit manually.",
            "// Source of truth: validated Canonical IR.",
            f"module {self.block.name} (",
        ]

        ports = [
            "    input  logic        PCLK",
            "    input  logic        PRESETn",
            "    input  logic        PSEL",
            "    input  logic        PENABLE",
            "    input  logic        PWRITE",
            "    input  logic [31:0] PADDR",
            "    input  logic [31:0] PWDATA",
            "    output logic [31:0] PRDATA",
            "    output logic        PREADY",
            "    output logic        PSLVERR",
        ]
        for register in self.block.registers:
            for field in register.fields:
                direction = "output" if field.access == "RW" else "input "
                ports.append(
                    f"    {direction} logic {_compact_range(field)}"
                    f"{_port_name(register, field)}"
                )

        lines.extend(
            f"{port}{',' if index < len(ports) - 1 else ''}"
            for index, port in enumerate(ports)
        )
        lines.extend([");", ""])

        lines.append("    // Local byte offsets")
        for register in self.block.registers:
            lines.append(
                f"    localparam logic [31:0] {_addr_name(register)} = "
                f"32'h{register.offset:08X};"
            )
        lines.append("")

        for register in self.block.registers:
            for field in register.fields:
                if field.access == "W1C":
                    lines.append(
                        f"    logic {_compact_range(field)}"
                        f"{_state_name(register, field)};"
                    )
        if any(
            field.access == "W1C"
            for register in self.block.registers
            for field in register.fields
        ):
            lines.append("")

        lines.extend([
            "    logic apb_access;",
            "    logic apb_write;",
            "    logic apb_read;",
            "    logic addr_misaligned;",
            "    logic addr_mapped;",
            "",
            "    assign PREADY          = 1'b1;",
            "    assign apb_access      = PSEL && PENABLE && PREADY;",
            "    assign apb_write       = apb_access && PWRITE;",
            "    assign apb_read        = apb_access && !PWRITE;",
            "    assign addr_misaligned = (PADDR[1:0] != 2'b00);",
        ])

        mapped_terms = [
            f"(PADDR == {_addr_name(register)})"
            for register in self.block.registers
        ]
        lines.append(f"    assign addr_mapped     = {mapped_terms[0]} ||")
        for term in mapped_terms[1:-1]:
            lines.append(f"                             {term} ||")
        if len(mapped_terms) > 1:
            lines.append(f"                             {mapped_terms[-1]};")
        else:
            lines[-1] = lines[-1][:-3] + ";"

        lines.extend([
            "    assign PSLVERR =",
            "        apb_access && (addr_misaligned || !addr_mapped);",
            "",
            "    // Combinational read path; uncovered bits remain zero.",
            "    always_comb begin",
            "        PRDATA = 32'b0;",
            "",
            "        if (apb_read && !addr_misaligned && addr_mapped) begin",
            "            case (PADDR)",
        ])
        for register in self.block.registers:
            lines.append(f"                {_addr_name(register)}: begin")
            for field in register.fields:
                source = (
                    _state_name(register, field)
                    if field.access == "W1C"
                    else _port_name(register, field)
                )
                lines.append(
                    f"                    PRDATA{_bus_slice(field)} = {source};"
                )
            lines.append("                end")
        lines.extend([
            "                default: PRDATA = 32'b0;",
            "            endcase",
            "        end",
            "    end",
            "",
        ])

        for register in self.block.registers:
            for field in register.fields:
                if field.access == "RW":
                    lines.extend(self._render_rw_field(register, field))
                elif field.access == "W1C":
                    lines.extend(self._render_w1c_field(register, field))

        lines.extend(["endmodule", ""])
        return "\n".join(lines)

    def write(self, output_path: str | Path) -> Path:
        path = Path(output_path)
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(self.render(), encoding="utf-8", newline="\n")
        return path

    @staticmethod
    def _render_rw_field(register: Register, field: Field) -> list[str]:
        port = _port_name(register, field)
        return [
            f"    // {register.name}.{field.name}: RW",
            "    always_ff @(posedge PCLK or negedge PRESETn) begin",
            "        if (!PRESETn) begin",
            f"            {port} <= {_sv_literal(field.width, field.reset)};",
            f"        end else if (apb_write && (PADDR == {_addr_name(register)})) begin",
            f"            {port} <= PWDATA{_bus_slice(field)};",
            "        end",
            "    end",
            "",
        ]

    @staticmethod
    def _render_w1c_field(register: Register, field: Field) -> list[str]:
        state = _state_name(register, field)
        set_port = _port_name(register, field)
        return [
            f"    // {register.name}.{field.name}: W1C; hardware set wins bitwise.",
            "    always_ff @(posedge PCLK or negedge PRESETn) begin",
            "        if (!PRESETn) begin",
            f"            {state} <= {_sv_literal(field.width, field.reset)};",
            f"        end else if (apb_write && (PADDR == {_addr_name(register)})) begin",
            f"            {state} <= ({state} & ~PWDATA{_bus_slice(field)}) | {set_port};",
            "        end else begin",
            f"            {state} <= {state} | {set_port};",
            "        end",
            "    end",
            "",
        ]
